### ISSUE TITLE
Add endpoint for adding items to an existing collection

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/VirtualCollectionRegistry#1]
For the purpose of integration with other tools, it would be useful to accept requests for adding an item to a (to be selected) existing collection owned by the current user. This should work roughly like the existing `/submit` resource (defined in the `VirtualCollectionFormSubmissionResource` class), which accepts POSTs with form parameters that define a new collection. The proposed resource would just take a list of URIs (also as a form parameter), which it would check, and then prompt the user (through an intermediate web page) to select one of their existing collections - optionally also allow to create a new one instead.

Integration from the side of the VLO would be the first use case for this functionality.

**Comment by dietervu** [comment]
Also requires further discussion of web-based interaction vs webservice-based interaction.

**Comment by dgbroeder** [comment]
if I am not mistaken this is also required (basis) for all the SSHOC 'search result basket' use-cases, so with ERIHs and CESSDA

**Comment by WillemElbers** [comment]
Released in https://github.com/clarin-eric/VirtualCollectionRegistry/releases/tag/1.6.0-rc1
