### ISSUE TITLE
 Mark PIDs with an actionable icon

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/VirtualCollectionRegistry#11]
As for the VLO (see https://github.com/clarin-eric/VLO/issues/173), make links that are (based on) PIDs (handles, DOIs, maybe also URNs) but not rendered as such for usability reasons should be 'decorated' with an icon that:

1. Indicates that the linked resource has a PID
1. Makes the PID visible somehow, e.g. in a dialogue that allows for copy/paste
1. Offers (a link to) explanation on what PIDs are and how they can be used

This could be applied in the list of resources in the collection and to the PID for the collection itself.

The icon could for instance just be a little box that says "PID".

**Comment by twagoo** [comment]
![screenshot 2018-11-13 at 13 24 34](https://user-images.githubusercontent.com/7011396/48413418-fdb51f00-e747-11e8-8f73-402df2d41cc8.png)

![screenshot 2018-11-13 at 13 28 37](https://user-images.githubusercontent.com/7011396/48413436-0ad20e00-e748-11e8-9c63-5b76f3b53bb5.png)

**Comment by WillemElbers** [comment]
A PID information panel similar to the one used in the VLO has been implement and is available since 1.2.0-alpha4 (also deployed on beta-vcr.clarin.eu)
