### ISSUE TITLE
Harmonize icons

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#117]
At the moment the favicon, the icon displayed in the menu bar and the icon on the clarin website differ. This should be harmonized.

**Comment by WillemElbers** [comment]
Any suggestion on which one to settle on? I assume the one from the website. Please comment if you have a different preference.

**Comment by dietervu** [comment]
Yes, the one from the website. Source: https://www.flaticon.com/free-icon/agenda_783161 (we do not need an attribution since we have a paid license)

**Comment by WillemElbers** [comment]
I also renamed the heading next to icon from `Virtual Collections` to `Virtual Collection Registry`. I think that is more in line with how the other services do it.

**Comment by WillemElbers** [comment]
https://github.com/clarin-eric/VirtualCollectionRegistry/commit/7298517cb3dcd9cef8e86ea3007d18749a2bb86a
