### ISSUE TITLE
Character encoding issue for title of DOI

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#139]
https://api.datacite.org/dois/application/x-bibtex/10.34733/vcr-1036

contains a title field:

`Signpost Demo Collection ? Bonner Gerontologische L�ngsschnittstudie (BOLSA), all recordings of subject 2608`

Looks like an encoding issue.

**Comment by WillemElbers** [comment]
Fixed in commit: https://github.com/clarin-eric/VirtualCollectionRegistry/commit/552b67346b6f9587a22ba91c3d2b08306c9c94e4.

Tested on collections.clarin-dev.eu with https://doi.test.datacite.org/dois/10.17907%2Fvc-beta1048
