### ISSUE TITLE
DOI resolution support

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#17]
The first link of http://hdl.handle.net/11372/VC-1017 is a DOI that gets resolved via hdl.handle.org - should be doi.org (eg https://doi.org/10.1075/jhl.16022.vio) instead.

**Comment by WillemElbers** [comment]
Fixed in https://github.com/clarin-eric/VirtualCollectionRegistry/commit/7bd1d6c5f917b96e0b9baa75897bc006d2932a72
