### ISSUE TITLE
Allow users to download the entire collection or selected parts thereof.

### ISSUE THREAD

**Issue by zinn-claus** [clarin-eric/VirtualCollectionRegistry#172]
Have a button/an action at collection level (not resource level) that allows users to download the contents of a collection (or a selection thereof). When users press, say, "Download collection", they are directed to CMDI Explorer where users can inspect the collection as a tree, and select those parts of interest for download. The VCR would need to call the CMDI Explorer as, for example, 

https://weblicht.sfs.uni-tuebingen.de/CMDIExplorer/input/#/vcr/http%3A%2F%2Fhdl.handle.net%2F11372%2FVC-1002

That is, the PID pointing to the collection is given to CMDIExplorer via URL encoding.

**Comment by WillemElbers** [comment]
First approach to implement CMDI explorer integration has been deployed in tag 1.8.1-alpha4 available on https://alpha-collections.clarin.eu/public?1
