### ISSUE TITLE
(de)collapsing a panel requires to click the text or the collapse icon

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#23]
it would be nicer to be able to do this by clicking anywhere in the title box of the panel instead

**Comment by WillemElbers** [comment]
Is fixed for the filter panel in the current beta deployment (https://beta-vcr.clarin.eu), will be applied to all collapsible panels for the next release

**Comment by WillemElbers** [comment]
Fixed in https://github.com/clarin-eric/VirtualCollectionRegistry/commit/f0e7857e9955c4d4b53d7ade125686f344c8a6c5
