### ISSUE TITLE
Encoding issues with Shibboleth Attributes

### ISSUE THREAD

**Issue by benhur1999** [clarin-eric/VirtualCollectionRegistry#3]
When the VCR grabs information from Shibboleth attributes (e.g. Organization, etc), the encoding is broken. AFAIK, Shibboleth exports those strings UTF-8 encoded.

How to reporduce:
 1. Login in via Shibboleth
 1. create a VC
 1. in the creator panel click "add me".

The string is malformed, if it contains e.g. umlauts.

**Comment by WillemElbers** [comment]
Solved in the shhaa filter: https://github.com/clarin-eric/mpgaai/releases/tag/1.0.7

Will be deployed in the beta vcr (beta-vcr.clarin.eu) with the next release (end 2018 / early 2019).
