### ISSUE TITLE
Popups on the "Create" page show up and disappear too fast

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/VirtualCollectionRegistry#30]
When moving the mouse arrow around the "Create" page, the help popups show up and disappear rather quickly making the interface look flickery. A certain delay could be introduced before the popup is shown to avoid this.

**Comment by WillemElbers** [comment]
Fixed in https://github.com/clarin-eric/VirtualCollectionRegistry/commit/866d39047ec2833dee1b3d1f01ec85d4387d908b
