### ISSUE TITLE
Handle info pop-up:  "This identifier resolves to: Unexpected HTTP response code"

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/VirtualCollectionRegistry#44]
For the references of https://beta-vcr.clarin.eu/app/details/1006, I see the following in the handle info pop-up:

![screenshot 2019-02-21 at 16 34 50](https://user-images.githubusercontent.com/7011396/53180785-9fc18e80-35f6-11e9-8ae3-23a356255b13.png)

Redirects should probably followed _or_ the user should not get to see a fairly raw error code _or_ it should at least be made clear that this is an error.

**Comment by WillemElbers** [comment]
Both HTTP 301 and 302 are now accepted.

Added a more high level error message is still an open issue. I would prefer an approach where the user is shown the high level message but there is an option to obtain the low level error as well.

Another observation is that the current implementation doesn't follow aliases. The handle is resolved exactly once and that response is shown in the UI and thus  might be another handle.
