### ISSUE TITLE
fix tooltip for Switchbaoard invocation

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#55]
Currently it says:

> Open this collection in the language resurce switchboard

Should be:

> Process this file with the language resource switchboard

Also the text should be centred, not justified.

Besides that, the Switchboard icon is very small. The tooltip does (obviously) not show up on mobile devices, so maybe we can think of another way of making it clear that this icon sends something to the switchboard on touch devices. Maybe the 3 dots as used in the VLO with a pop-up stating in text + icon "Process wit language resource switchboard"? Would definitely be more uniform.

**Comment by WillemElbers** [comment]
The vlo approach has been implemented and the tooltip has been removed since the popup is descriptive enough.
