### ISSUE TITLE
General pane not very mobile-friendly

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#56]
Long descriptions are rendered too narrowly, see screenshot attached.
![screenshot_2019-02-27 clarin virtual collection registry](https://user-images.githubusercontent.com/8073487/53492506-53b09700-3a99-11e9-9873-01d5d0f0f177.png)

**Comment by WillemElbers** [comment]
Switching to a more vertical layout (labels above the content fields) will improve this quite a bit. Can also be adjusted for smaller screen size only.

**Comment by WillemElbers** [comment]
Made improvements so that the horizontal layout is switched to a vertical layout when scaling down. See #d590d62
