### ISSUE TITLE
Create less technical help page

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#63]
https://collections.clarin.eu/app/help is very technical. Needs some explanation for laymen.

**Comment by WillemElbers** [comment]
Will be reworked after simplifying the data model to match all changes.

**Comment by dietervu** [comment]
Part of the documentation can be provided on the CLARIN website

**Comment by WillemElbers** [comment]
First shot at rewriting the help page: https://github.com/clarin-eric/VirtualCollectionRegistry/commit/5761d7aa32f6e55533fdbf3f1472195a446b5507
