### ISSUE TITLE
Add EOSC-hub funding information to about page

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/VirtualCollectionRegistry#77]
As requested by Deborah:

```
In order to address one of the project review recommendations, the PO
is asking all services which receive funding from EOSC-hub to
acknowledge the project.

I thus kindly ask you for each service and repository page
(i.e.github) to state in visible way: "This work is co-funded by the
EOSC-hub project (Horizon 2020) under Grant number 777536."
```

**Comment by dietervu** [comment]
For the VCR we can use the wording as proposed by the VLO about text, including also a reference to CLARIN-PLUS: vlo.clarin.eu/about

**Comment by WillemElbers** [comment]
Implemented in https://github.com/clarin-eric/VirtualCollectionRegistry/commit/3caf7ab293e1acac73958dd107cc30510e652a3f and deployed on https://collections.clarin-dev.eu/. Will be deployed on production next week.
