### ISSUE TITLE
Improve application of CLARIN style

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/VirtualCollectionRegistry#8]
Reported by Dieter:
* Color of tooltips should match style (currently black instead of blue
* Font (of tooltips?) doesn't match (incorrect font used)
* Typo in tooltip LRS icon ( resurce instead of resource)

**Comment by dietervu** [comment]
The font used in the menu and filtering pane is still Roboto and not the CLARIN Source Sans Pro.

**Comment by WillemElbers** [comment]
Updated all fonts to `font-family: "Source Sans Pro", Calibri, Arial, Helvetica sans-serif;`

**Comment by WillemElbers** [comment]
The layout has been vastly improved in the current beta instance and this will be deployed in production today. Closing for now, if any specific issues arise, please make individual tickets.
