### ISSUE TITLE
Beta VCR: firefox rendering issues

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#9]
https://beta-vcr.clarin.eu/ causes several rendering issues in firefox which are not perceivable in chrome:

- collapse button does not work
- clicking on VCR title to see details does not work

**Comment by WillemElbers** [comment]
Safari is working as intended.

**Comment by WillemElbers** [comment]
Looks fixed after fixing the "show details" isse: cb8685b215c85d8ff9b16945179f5ffa94f43383

**Comment by dietervu** [comment]
Yes, seems fixed now. Cannot reproduce the issues anymore.
