### ISSUE TITLE
Less stringent warning messages on publishing non-PID links

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#94]
_Publication of the collection in its current state is not recommended. Would you still like to publish the collection?_

We should rethink this message, and rather suggest/recommend to use PIDs where possible.

**Comment by WillemElbers** [comment]
Same as #113

**Comment by WillemElbers** [comment]
Warnings about links are now moved into the editor and turned into a recommendation: https://github.com/clarin-eric/VirtualCollectionRegistry/commit/8512a36765d22fe410d9f2f6a06eab24cf654ec0
