### ISSUE TITLE
Support markdown in description text

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/VirtualCollectionRegistry#95]
similar to the LRS tool metadata fields, markdown support would be nice

**Comment by WillemElbers** [comment]
Options for markdown parsers:

**Comment by WillemElbers** [comment]
Has been implemented for the collection description field. Will also update the reproducibility notice and reference description fields.

**Comment by WillemElbers** [comment]
Enabled markdown in reproducibility notice field and reference description fields: https://github.com/clarin-eric/VirtualCollectionRegistry/commit/ea49f841b1a2aaaa5917605fde19a39f3a6cb48e
